all:build

build:

	g++ -Wall -I./include -L./lib '.\proyectoLp.cpp' -o '.\proyectoLp.exe' -lraylib -lopengl32 -lgdi32 -lwinmm
	g++ -Wall -I./include -L./lib '.\prueba.cpp' -o '.\prueba.exe' -lraylib -lopengl32 -lgdi32 -lwinmm
	g++ -Wall -I./include -L./lib '.\tiempo.cpp' -o '.\tiempo.exe' -lraylib -lopengl32 -lgdi32 -lwinmm
	
gatito:

	rm *.exe

