all:build

build:

	g++ -Wall -I./include -L./lib '.\proyectoLp.cpp' -o '.\proyectoLp.exe' -lraylib -lopengl32 -lgdi32 -lwinmm
	g++ -Wall -I./include -L./lib '.\proyectoSCLp.cpp' -o '.\proyectoSCLp.exe' -lraylib -lopengl32 -lgdi32 -lwinmm
	proyectoLp.exe
	
gatito:

	rm *.exe

